### ISSUE TITLE
Reloaders Workshop bug, Inventory sheet not adding up 

### ISSUE THREAD

**Issue by Fooney** [lobobeebe/ReloadersWorkshop#6]
In this program I have found a bug in printing the Cost Analysis sheet for the powder.  All other components see to be OK.  Issue is, you put say 1 pound of powder into  inventory,  use maybe 1/2 pound up and the inventory sheet still show 1 pound.   
[ReloadUserGuide (2).PDF](https://github.com/lobobeebe/ReloadersWorkshop/files/3100591/ReloadUserGuide.2.PDF)
![ReloadersWorkShopSetup](https://user-images.githubusercontent.com/49099842/56462200-6e5a0a80-637c-11e9-925b-1c5338c1308e.gif)  Change this to .exe from .gif
![Backup 2019-04-15 at 153317](https://user-images.githubusercontent.com/49099842/56462213-a5c8b700-637c-11e9-9d60-3eb2ff438586.gif)  Change this to .rwb  from .gif

After loading the backup file, and then printing out the Cost analysis sheet, notice that the Varget and Hogdon H4895 show what was the original amount inventoried under the remaining amount =to both being the same,  just to the right of the same row is the amount that should be subtracted from the original amount to show correct remaining amount. Other components  are listed correctly.   Hope I was able to explain that well enough.

There are several youtube videos for this program online.
Unfortunately the author of this program died recently and his son put the program on Github for anyone to use and fix bugs.  I have found only 1 bug as I have stated.
I know absolutely nothing about programming but would appreciate someone being able to fix this bug.  This program use to be registered for $16.00 USD until the authors son put it on here to be use for free. 
Sorry my computer skills are limited (66 years old) or I would try and fix it.  But it's all gibberish to me. 

Thank you in advance 
Dave

**Comment by rvicta** [comment]
I have been working on learning the code base for the program and will shortly start working on fixes. I emailed Cody to let him know that I am interested in taking care of maintenance of the program.

**Comment by Fooney** [comment]
Rvicta 

Thank you so much for taking this program on.  Kudos to you.

Dave

**Comment by rvicta** [comment]
I'm trying to replicate your issue. Could you possibly provide me a PDF of what your Cost Analysis looks like. Or even better, a screen shot of the Cost Analysis and also of the options screen that comes up before the Cost Analysis is displayed. Thanks.

**Comment by Fooney** [comment]
Here is the screen capture of the errors.  Along the Varget row it shows What I originally purchased.  Under the used column It s   shows the amount I started with (purchased not used)   The remaining column is right I believe.  Same as for  the H4895 row.

This is under the supplies option then the  cost analysis button, and the page with the error is after you print the inventory.
All the other supplies in inventory seem to show correctly, i.e. primer, cases, etc.  Jut the Powder part of the inventory sheet is wrong.
I have enclosed a backup file so that all things I have entered can be put into the program without all the typing.

Hopefully I have explained it properly.

Thanks
Dave


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by Fooney** [comment]
[Cost analysis.docx](https://github.com/lobobeebe/ReloadersWorkshop/files/3195836/Cost.analysis.docx)
![Backup 2019-05-19 at 175146](https://user-images.githubusercontent.com/49099842/57990397-91eba000-7a63-11e9-8ae9-7a6ae4e74006.gif)


Change the .gif file to .rwb file for it to work.   Couldn't send a .rwb file.

Dave

**Comment by rvicta** [comment]
Okay, fixed it. Now trying to figure out how to upload the executable only.

When the domain name for reloadersworkshop.com comes up for renewal I'm hoping that Cody lets it expire so I can get it. I contacted Cody about letting me into the current site so I can upload executables for download but he hasn't responded yet.

**Comment by Fooney** [comment]
Hope you can take over from Cody's father.  It is a great program, a lot of work was put into it.  Cody maybe still has a list of people who originally purchased the program that he used to contact us with when he decided to move the program to Github.,  One may find more little errors or such that can be improved on.  I for one love this program,  and have only found 1 error, but there could be a few others , or not.

Dave

**Comment by Fooney** [comment]
Rvicta

Can you keep apprised of your progress for this software.

Thanks
Dave


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by rvicta** [comment]
So, one of the updates that Kevin had listed was a fix to the PDF download/view. I just fixed that. The web URL for the documents is now an application property and not hard coded into the application. At some point I will come up with an update mechanism to take care of whenever the SAAMI organization decides to change the directory structure, as they did when it stopped working in the application. The page number has not been implemented. At some point I will do that.

**Comment by Fooney** [comment]
Thank you for the update,  do let me know when you can release a new version with the fixes that is ready for downloading.

Thanks again
Dave


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by Fooney** [comment]
Rvicta
Just wondering how you're coming along with this program.

Thanks
Dave


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by rvicta** [comment]
I'm still working on the website for the download. It will end up looking like the same site since the software is still basically the same.

Also, fixed a couple more issues.

**Comment by Fooney** [comment]
Nice to hear.  Will it be the same website address as before Kevin died.

Thanks
Dave


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by rvicta** [comment]
Well, if I can get the new site up and running soon it will be a different address. Just a .net instead of .com. I already have the address. Otherwise, if I still don't have it running by the time the expiration comes up on the original address I may also purchase that one and then either one could be used. Also, found a bug in the program that didn't show up till I took care of one of the "To Do" items. 

I'm currently working through the installer to figure out how Kevin set it up.

**Comment by Fooney** [comment]
Thank you keeping us posted.  Bet you'll be glad when it's done.

Dave


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by rvicta** [comment]
Hi Dave.
Since I have the new domain you can email me instead of communicating in here. Just use "rvicta@reloadersworkshop.net". Something I'm working on now is the default installation directory and having the installation recognize that there was a previous version of the program and moving the database .
Anyway, I will let you know when I have a version that is ready for distribution.
Reuel
