### ISSUE TITLE
Compilation of latest version and recovering old backups

### ISSUE THREAD

**Issue by angellxp** [lobobeebe/ReloadersWorkshop#7]
What are you using to compile this?  I used VS and it seems to have worked.  

Trying to restore the backup file from about a year ago did not work through the build I compiled.  Am I doing something wrong? 
I can start over if need be this time but I want to be sure this is not a bug in the latest build. Could it have something to do with the way I compiled it?

Thanks for the support in keeping this program up and running.

**Comment by rvicta** [comment]
I know this is a few months old but I just wanted to provide you with an answer. I use Visual Studio to compile the program. At some point Kevin Beebe changed the structure of the data file and I have a feeling he had a utility to update the data structure for older data files. The import functionality in his last release was never completed. I have basically taken over continuing development and support of the software. I have fixed most of the bugs that were in the latest ReadMe file and some that other users have found. I will be changing from the encrypted serialized data file to an embedded database to make life easier for me.

**Comment by phunter00** [comment]
Thanks, but I've migrated to Gordon's Reloading Tool...

Regards,

Perry

**Comment by angellxp** [comment]
Thanks for the update. I'll download a fresh copy tonight. I for one very much appreciate the work your putting I to keeping this program up and running. If I were were more proficient with VS I'd offer to help... 

So does this mean old files won't be usable?  If not that's ok. Onward and upward. Thanks again

**Comment by angellxp** [comment]
Keep up the good work!
